// automatically generated by the FlatBuffers compiler, do not modify


#ifndef FLATBUFFERS_GENERATED_INPUT_STARDUSTXR_H_
#define FLATBUFFERS_GENERATED_INPUT_STARDUSTXR_H_

#include "flatbuffers/flatbuffers.h"
#include "flatbuffers/flexbuffers.h"

#include "HandInput.hpp"
#include "PointerInput.hpp"
#include "common.hpp"

namespace StardustXR {

struct InputData;
struct InputDataBuilder;

enum class InputDataRaw : uint8_t {
  NONE = 0,
  Pointer = 1,
  Hand = 2,
  MIN = NONE,
  MAX = Hand
};

inline const InputDataRaw (&EnumValuesInputDataRaw())[3] {
  static const InputDataRaw values[] = {
    InputDataRaw::NONE,
    InputDataRaw::Pointer,
    InputDataRaw::Hand
  };
  return values;
}

inline const char * const *EnumNamesInputDataRaw() {
  static const char * const names[4] = {
    "NONE",
    "Pointer",
    "Hand",
    nullptr
  };
  return names;
}

inline const char *EnumNameInputDataRaw(InputDataRaw e) {
  if (flatbuffers::IsOutRange(e, InputDataRaw::NONE, InputDataRaw::Hand)) return "";
  const size_t index = static_cast<size_t>(e);
  return EnumNamesInputDataRaw()[index];
}

template<typename T> struct InputDataRawTraits {
  static const InputDataRaw enum_value = InputDataRaw::NONE;
};

template<> struct InputDataRawTraits<StardustXR::Pointer> {
  static const InputDataRaw enum_value = InputDataRaw::Pointer;
};

template<> struct InputDataRawTraits<StardustXR::Hand> {
  static const InputDataRaw enum_value = InputDataRaw::Hand;
};

bool VerifyInputDataRaw(flatbuffers::Verifier &verifier, const void *obj, InputDataRaw type);
bool VerifyInputDataRawVector(flatbuffers::Verifier &verifier, const flatbuffers::Vector<flatbuffers::Offset<void>> *values, const flatbuffers::Vector<InputDataRaw> *types);

struct InputData FLATBUFFERS_FINAL_CLASS : private flatbuffers::Table {
  typedef InputDataBuilder Builder;
  static FLATBUFFERS_CONSTEXPR_CPP11 const char *GetFullyQualifiedName() {
    return "StardustXR.InputData";
  }
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_UUID = 4,
    VT_INPUT_TYPE = 6,
    VT_INPUT = 8,
    VT_DISTANCE = 10,
    VT_DATAMAP = 12
  };
  const flatbuffers::String *uuid() const {
    return GetPointer<const flatbuffers::String *>(VT_UUID);
  }
  flatbuffers::String *mutable_uuid() {
    return GetPointer<flatbuffers::String *>(VT_UUID);
  }
  StardustXR::InputDataRaw input_type() const {
    return static_cast<StardustXR::InputDataRaw>(GetField<uint8_t>(VT_INPUT_TYPE, 0));
  }
  const void *input() const {
    return GetPointer<const void *>(VT_INPUT);
  }
  template<typename T> const T *input_as() const;
  const StardustXR::Pointer *input_as_Pointer() const {
    return input_type() == StardustXR::InputDataRaw::Pointer ? static_cast<const StardustXR::Pointer *>(input()) : nullptr;
  }
  const StardustXR::Hand *input_as_Hand() const {
    return input_type() == StardustXR::InputDataRaw::Hand ? static_cast<const StardustXR::Hand *>(input()) : nullptr;
  }
  void *mutable_input() {
    return GetPointer<void *>(VT_INPUT);
  }
  float distance() const {
    return GetField<float>(VT_DISTANCE, 0.0f);
  }
  bool mutate_distance(float _distance = 0.0f) {
    return SetField<float>(VT_DISTANCE, _distance, 0.0f);
  }
  const flatbuffers::Vector<uint8_t> *datamap() const {
    return GetPointer<const flatbuffers::Vector<uint8_t> *>(VT_DATAMAP);
  }
  flatbuffers::Vector<uint8_t> *mutable_datamap() {
    return GetPointer<flatbuffers::Vector<uint8_t> *>(VT_DATAMAP);
  }
  flexbuffers::Reference datamap_flexbuffer_root() const {
    return flexbuffers::GetRoot(datamap()->Data(), datamap()->size());
  }
  bool Verify(flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyOffsetRequired(verifier, VT_UUID) &&
           verifier.VerifyString(uuid()) &&
           VerifyField<uint8_t>(verifier, VT_INPUT_TYPE, 1) &&
           VerifyOffsetRequired(verifier, VT_INPUT) &&
           VerifyInputDataRaw(verifier, input(), input_type()) &&
           VerifyField<float>(verifier, VT_DISTANCE, 4) &&
           VerifyOffset(verifier, VT_DATAMAP) &&
           verifier.VerifyVector(datamap()) &&
           flexbuffers::VerifyNestedFlexBuffer(datamap(), verifier) &&
           verifier.EndTable();
  }
};

template<> inline const StardustXR::Pointer *InputData::input_as<StardustXR::Pointer>() const {
  return input_as_Pointer();
}

template<> inline const StardustXR::Hand *InputData::input_as<StardustXR::Hand>() const {
  return input_as_Hand();
}

struct InputDataBuilder {
  typedef InputData Table;
  flatbuffers::FlatBufferBuilder &fbb_;
  flatbuffers::uoffset_t start_;
  void add_uuid(flatbuffers::Offset<flatbuffers::String> uuid) {
    fbb_.AddOffset(InputData::VT_UUID, uuid);
  }
  void add_input_type(StardustXR::InputDataRaw input_type) {
    fbb_.AddElement<uint8_t>(InputData::VT_INPUT_TYPE, static_cast<uint8_t>(input_type), 0);
  }
  void add_input(flatbuffers::Offset<void> input) {
    fbb_.AddOffset(InputData::VT_INPUT, input);
  }
  void add_distance(float distance) {
    fbb_.AddElement<float>(InputData::VT_DISTANCE, distance, 0.0f);
  }
  void add_datamap(flatbuffers::Offset<flatbuffers::Vector<uint8_t>> datamap) {
    fbb_.AddOffset(InputData::VT_DATAMAP, datamap);
  }
  explicit InputDataBuilder(flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  flatbuffers::Offset<InputData> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = flatbuffers::Offset<InputData>(end);
    fbb_.Required(o, InputData::VT_UUID);
    fbb_.Required(o, InputData::VT_INPUT);
    return o;
  }
};

inline flatbuffers::Offset<InputData> CreateInputData(
    flatbuffers::FlatBufferBuilder &_fbb,
    flatbuffers::Offset<flatbuffers::String> uuid = 0,
    StardustXR::InputDataRaw input_type = StardustXR::InputDataRaw::NONE,
    flatbuffers::Offset<void> input = 0,
    float distance = 0.0f,
    flatbuffers::Offset<flatbuffers::Vector<uint8_t>> datamap = 0) {
  InputDataBuilder builder_(_fbb);
  builder_.add_datamap(datamap);
  builder_.add_distance(distance);
  builder_.add_input(input);
  builder_.add_uuid(uuid);
  builder_.add_input_type(input_type);
  return builder_.Finish();
}

inline flatbuffers::Offset<InputData> CreateInputDataDirect(
    flatbuffers::FlatBufferBuilder &_fbb,
    const char *uuid = nullptr,
    StardustXR::InputDataRaw input_type = StardustXR::InputDataRaw::NONE,
    flatbuffers::Offset<void> input = 0,
    float distance = 0.0f,
    const std::vector<uint8_t> *datamap = nullptr) {
  auto uuid__ = uuid ? _fbb.CreateString(uuid) : 0;
  auto datamap__ = datamap ? _fbb.CreateVector<uint8_t>(*datamap) : 0;
  return StardustXR::CreateInputData(
      _fbb,
      uuid__,
      input_type,
      input,
      distance,
      datamap__);
}

inline bool VerifyInputDataRaw(flatbuffers::Verifier &verifier, const void *obj, InputDataRaw type) {
  switch (type) {
    case InputDataRaw::NONE: {
      return true;
    }
    case InputDataRaw::Pointer: {
      auto ptr = reinterpret_cast<const StardustXR::Pointer *>(obj);
      return verifier.VerifyTable(ptr);
    }
    case InputDataRaw::Hand: {
      auto ptr = reinterpret_cast<const StardustXR::Hand *>(obj);
      return verifier.VerifyTable(ptr);
    }
    default: return true;
  }
}

inline bool VerifyInputDataRawVector(flatbuffers::Verifier &verifier, const flatbuffers::Vector<flatbuffers::Offset<void>> *values, const flatbuffers::Vector<InputDataRaw> *types) {
  if (!values || !types) return !values && !types;
  if (values->size() != types->size()) return false;
  for (flatbuffers::uoffset_t i = 0; i < values->size(); ++i) {
    if (!VerifyInputDataRaw(
        verifier,  values->Get(i), types->GetEnum<InputDataRaw>(i))) {
      return false;
    }
  }
  return true;
}

inline const StardustXR::InputData *GetInputData(const void *buf) {
  return flatbuffers::GetRoot<StardustXR::InputData>(buf);
}

inline const StardustXR::InputData *GetSizePrefixedInputData(const void *buf) {
  return flatbuffers::GetSizePrefixedRoot<StardustXR::InputData>(buf);
}

inline InputData *GetMutableInputData(void *buf) {
  return flatbuffers::GetMutableRoot<InputData>(buf);
}

inline StardustXR::InputData *GetMutableSizePrefixedInputData(void *buf) {
  return flatbuffers::GetMutableSizePrefixedRoot<StardustXR::InputData>(buf);
}

inline bool VerifyInputDataBuffer(
    flatbuffers::Verifier &verifier) {
  return verifier.VerifyBuffer<StardustXR::InputData>(nullptr);
}

inline bool VerifySizePrefixedInputDataBuffer(
    flatbuffers::Verifier &verifier) {
  return verifier.VerifySizePrefixedBuffer<StardustXR::InputData>(nullptr);
}

inline void FinishInputDataBuffer(
    flatbuffers::FlatBufferBuilder &fbb,
    flatbuffers::Offset<StardustXR::InputData> root) {
  fbb.Finish(root);
}

inline void FinishSizePrefixedInputDataBuffer(
    flatbuffers::FlatBufferBuilder &fbb,
    flatbuffers::Offset<StardustXR::InputData> root) {
  fbb.FinishSizePrefixed(root);
}

}  // namespace StardustXR

#endif  // FLATBUFFERS_GENERATED_INPUT_STARDUSTXR_H_
